#!/usr/bin/env sh

BASEDIR=$(dirname "$0")

# 
# Show number of fsevent processes running
# 
FSEVENT_COUNT=$(ps -ef | grep "fsevent*" | grep -v grep | wc -l)
echo "fsevent: ${FSEVENT_COUNT}"

echo ""
echo ""

# 
# Show local and wan ip addresses
# 
IP_INFO=$($BASEDIR/ipinfo)
echo "$IP_INFO"
