#!/usr/bin/env bash

# Installs tools for Android development environment

# Android
brew cask install android-studio
brew cask install android-sdk
brew cask install android-ndk

SHELL_FILE=
if [[ $(echo $0) == "-bash" ]]; then
  if [[ -f "$HOME/.bashrc" ]]; then
    SHELL_FILE="$HOME/.bashrc"
  else
    SHELL_FILE="$HOME/.bash_profile"
  fi
elif [[ $(echo $0) == "-zsh" ]]; then
  SHELL_FILE="$HOME/.zshrc"
else
  echo "I don't know what shell you are using."
  exit 1
fi

# echo "export ANDROID_HOME=$HOME/Library/Android/sdk" >> $SHELL_FILE
echo "export ANDROID_HOME=/usr/local/share/android-sdk" >> $SHELL_FILE
echo "export ANDROID_SDK_ROOT=/usr/local/share/android-sdk" >> $SHELL_FILE
echo "export PATH=$PATH:$ANDROID_HOME/emulator" >> $SHELL_FILE
echo "export PATH=$PATH:$ANDROID_HOME/tools" >> $SHELL_FILE
echo "export PATH=$PATH:$ANDROID_HOME/tools/bin" >> $SHELL_FILE
echo "export PATH=$PATH:$ANDROID_HOME/platform-tools" >> $SHELL_FILE

echo "All done."
